# Workflow to demonstrate parallel execution with self-hosted runners and 1-minute jobs

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job 1
  build-1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Start Job 1
        run: |
          echo "This is job 1."
          echo "Starting 1-minute wait on runner $(hostname)..."
          sleep 60
          echo "Job 1 complete!"

  # Job 2
  build-2:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Start Job 2
        run: |
          echo "This is job 2."
          echo "Starting 1-minute wait on runner $(hostname)..."
          sleep 60
          echo "Job 2 complete!"

  # Job 3
  build-3:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Start Job 3
        run: |
          echo "This is job 3."
          echo "Starting 1-minute wait on runner $(hostname)..."
          sleep 60
          echo "Job 3 complete!"
